version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/organization-backend:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost
      DATABASE_NAME: postgres

    # for rust debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: service:backend

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: servers.json
        target: /var/lib/pgadmin/servers.json
      - source: pgpass
        target: /pgpass
    network_mode: service:backend

configs:
  pgpass:
    content: localhost:5432:*:postgres:postgress
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "postgres",
            "Host": "localhost",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }
